enum ActionTypes {
  PERSONAL_INFO = 'PERSONAL_INFO',
  DOCUMENT = 'DOCUMENT',
  IMAGE_PREVIEW= 'IMAGE_PREVIEW',
  CURRENT_SLIDE= 'CURRENT_SLIDE',
  BANK_CARDS= 'BANK_CARDS',
  EDITING_BASE_INFO= 'EDITING_BASE_INFO',
}
export default ActionTypes;
